---
- name: Security Compliance & Auto-Remediation (Firewall)
  hosts: all
  become: yes                 # CRITICAL: Runs commands as root (sudo)
  gather_facts: yes           # Needed to detect OS type
  tasks:

    # =======================================
    # 1. Ubuntu / Debian Remediation (Shell Method)
    # =======================================
    - name: Check UFW Status (Ubuntu)
      command: ufw status
      register: ufw_check
      changed_when: false
      ignore_errors: yes
      when: ansible_os_family == 'Debian'

    - name: Enable UFW (Force Enable)
      command: ufw --force enable
      when: 
        - ansible_os_family == 'Debian'
        - "'Status: active' not in ufw_check.stdout"
      register: ufw_action

    - name: Report UFW Enabled
      debug:
        msg: "COMPLIANCE FIXED: UFW Firewall was inactive and has been ENABLED."
      when: 
        - ansible_os_family == 'Debian'
        - ufw_action.changed

    # =======================================
    # 2. RedHat / CentOS Remediation
    # =======================================
    - name: Start & Enable Firewalld (RHEL/CentOS)
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'

    # =======================================
    # 3. Windows Remediation
    # =======================================
    - name: Enable Windows Firewall
      win_shell: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
      when: ansible_os_family == 'Windows'
