---
- name: Security Compliance Check (Firewall Status)
  hosts: all
  become: yes                 # <--- CRITICAL: Runs commands as root (sudo)
  gather_facts: yes
  tasks:

    # -------------------------------------------
    # 1. Ubuntu / Debian Specific Check (UFW)
    # -------------------------------------------
    - name: Check UFW Status (Ubuntu/Debian)
      command: ufw status
      register: ufw_result
      changed_when: false
      ignore_errors: yes
      when: ansible_os_family == 'Debian'

    # If UFW is inactive (or disabled), fail the compliance check
    - name: Fail if UFW is inactive
      fail:
        msg: "COMPLIANCE FAILED: UFW (Firewall) is inactive on {{ inventory_hostname }}"
      when: 
        - ansible_os_family == 'Debian'
        - "'Status: active' not in ufw_result.stdout"

    # If UFW is active, pass the check
    - name: Pass if UFW is active
      debug:
        msg: "COMPLIANCE PASSED: UFW is ACTIVE on {{ inventory_hostname }}"
      when: 
        - ansible_os_family == 'Debian'
        - "'Status: active' in ufw_result.stdout"

    # -------------------------------------------
    # 2. RHEL / CentOS Specific Check (Firewalld)
    # -------------------------------------------
    - name: Check Firewalld Status (RHEL/CentOS)
      command: firewall-cmd --state
      register: rhel_firewall
      changed_when: false
      ignore_errors: yes
      when: ansible_os_family == 'RedHat'

    - name: Fail if Firewalld is inactive
      fail:
        msg: "COMPLIANCE FAILED: Firewalld is inactive on {{ inventory_hostname }}"
      when: 
        - ansible_os_family == 'RedHat'
        - rhel_firewall.rc != 0

    # -------------------------------------------
    # 3. Windows Specific Check (Windows Firewall)
    # -------------------------------------------
    - name: Check Windows Firewall
      win_shell: Get-NetFirewallProfile -Profile Domain | Select-Object -ExpandProperty Enabled
      register: win_firewall
      when: ansible_os_family == 'Windows'

    - name: Fail if Windows Firewall is down
      fail:
        msg: "COMPLIANCE FAILED: Domain Firewall is inactive on {{ inventory_hostname }}"
      when: 
        - ansible_os_family == 'Windows' 
        - "'True' not in win_firewall.stdout"
