---
- name: Remediate Bare Pod OOM (High Reliability SSH)
  hosts: all
  # Logs in as root via your AWX credential, then switches to your user
  become: yes
  become_user: akshay
  gather_facts: false
  vars:
    target_pod_name: "oom-test-pod"
    target_namespace: "demo"
    # Bumped to 1.5Gi to finally stabilize the tail /dev/zero process
    new_memory_limit: "1536Mi" 
    kubeconfig_path: "/home/akshay/.kube/config"

  tasks:
    - name: Cleanup stale JSON files
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - "raw_pod.json"
        - "remediate_pod.json"

    - name: Fetch current pod spec from Kubernetes
      ansible.builtin.shell: |
        kubectl get pod {{ target_pod_name }} -n {{ target_namespace }} -o json > /tmp/raw_pod.json
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        PATH: "/usr/local/bin:/usr/bin:/bin:/home/akshay/bin"

    - name: Patch Spec with Python (Ensures 1.5Gi limit is applied)
      ansible.builtin.shell: |
        python3 -c '
        import json, sys
        with open("/tmp/raw_pod.json", "r") as f:
            pod = json.load(f)
        
        # 1. Strip all unique/immutable identifiers so we can recreate it
        meta = pod.get("metadata", {})
        for k in ["uid", "resourceVersion", "creationTimestamp", "managedFields", "ownerReferences", "selfLink"]:
            meta.pop(k, None)
        pod["metadata"] = meta
        
        # 2. Strip the status field to prevent state conflicts
        pod.pop("status", None)

        # 3. Apply the massive 1.5Gi memory limit to ALL containers
        for container in pod["spec"]["containers"]:
            container["resources"] = {
                "limits": {"memory": "{{ new_memory_limit }}"},
                "requests": {"memory": "{{ new_memory_limit }}"}
            }
        
        with open("/tmp/remediate_pod.json", "w") as f:
            json.dump(pod, f)
        '
      args:
        chdir: /home/akshay

    - name: Force Delete failing pod (Immediate Eviction)
      ansible.builtin.shell: |
        kubectl delete pod {{ target_pod_name }} -n {{ target_namespace }} --force --grace-period=0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        PATH: "/usr/local/bin:/usr/bin:/bin"

    - name: Recreate Pod with New Limits
      ansible.builtin.shell: |
        kubectl create -f /tmp/remediate_pod.json
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        PATH: "/usr/local/bin:/usr/bin:/bin"

    - name: Wait for Pod to stabilize
      ansible.builtin.shell: |
        kubectl get pod {{ target_pod_name }} -n {{ target_namespace }}
      register: pod_status
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      delay: 5
      retries: 3
      until: "'Running' in pod_status.stdout"
